vagrant: add box_url for more stable downloading of the centos/7 box
Sometimes the CentOS CI fails to download the centos/7 box. By setting
the box_url, it should be able to download it from the correct location.

If this happens, the following error is displayed:
    Bringing machine 'master' up with 'libvirt' provider...
    ==> master: Box 'centos/7' could not be found. Attempting to find and install...
        master: Box Provider: libvirt
        master: Box Version: >= 0
    ==> master: An error occurred. The error will be shown after all tasks complete.
    An error occurred while executing the action on the 'master'
    machine. Please handle this error then try again:

    The box 'centos/7' could not be found or
    could not be accessed in the remote catalog. If this is a private
    box on HashiCorp's Atlas, please verify you're logged in via
    `vagrant login`. Also, please double-check the name. The expanded
    URL and error message are shown below:

    URL: ["https://atlas.hashicorp.com/centos/7"]
    Error: The requested URL returned error: 404 Not Found

The https://atlas.hashicorp.com/centos/7 URL really does not exist,
instead https://app.vagrantup.com/centos/7 should be used.

Signed-off-by: Niels de Vos <ndevos@redhat.com>