Fix yaml alignment issue
The deployer fails to deploy because on yaml alignment issue:

```
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
error: error validating "./kube-templates/heketi-deployment.yaml": error validating data: [found invalid field data for v1.ObjectMeta, found invalid field type for v1.ObjectMeta]; if you choose to ignore these errors, turn validation off with --validate=false
Waiting for heketi pod to start ... Timed out waiting for pods matching 'glusterfs=heketi-pod'.
the server doesn't have a resource type "dc"
serviceaccount "heketi-service-account" deleted
Error from server (NotFound): secrets "heketi-db-backup" not found
```